// Pixel-art icons: one 24x24 drawing per offer, given a thin slab
// of thickness behind it and hung in the totem's column of light.
//
// WHAT THIS IS
//   Every icon is FLAT art - no volume, no perspective, no sculpting - with a
//   few pixels of extrusion behind the face, like a thick cutout floating in
//   the light. The art is 2D. Only the object is 3D.
//
// WHY A GRID
//   The old 3D catalogue was hand-placed floats, so stroke weight, size and
//   density drifted from icon to icon and consistency had to be re-eyeballed
//   sixty-five times. A fixed grid makes it structural: every icon gets the
//   same 24x24 of room, the same one-pixel stroke, the same generated outline,
//   and the same light coming from the upper left. Two icons cannot disagree
//   about how thick a line is.
//
// WHY 24
//   16 is the classic, but this pool has whole families of near neighbours -
//   venom, neurotoxin, malady, antidote - that collapse into one blob at 16.
//   32 has room for detail nobody can see from across the arena. 24 is the
//   size where a drum still reads as a different object from a box magazine
//   and every art-pixel still lands on 2-3 screen pixels at range.
//
// THE OUTLINE IS GENERATED, NOT DRAWN
//   An icon's identity cannot be its negative space: the totem's additive
//   light fills in any gap you were meant to see through. A near-black outline
//   answers that directly - it is opaque geometry, not a hole - and generating
//   it from the silhouette means it is exactly one pixel everywhere, for free.
//
// EDITING THE ART
//   Item drawings live beside their definitions in js/items/. The small table
//   below holds only non-item drawings and is generated from tools/pixelart.
//   Edit those shapes there and run python3 tools/pixelart/build.py.

import * as THREE from 'three';
import { PASSIVE_ITEM_ICONS } from './items/passive/index.js';
import { ACTIVE_ITEM_ICONS } from './items/active/index.js';
import { DONATION_ITEM_ICONS } from './items/donation/index.js';

export const GRID = 24;
// One art-pixel in metres. 24 of them come to ~0.62m, matching the size the
// totems are built to expect (see ICON_SCALE in totems.js).
const PX = 0.026;
// Thickness: three art-pixels. Enough to read as a solid object turning in the
// light, not so much that the side walls compete with the face for attention.
const DEPTH = 3 * PX;

// TONES. Authored art names these; '0' also appears where a drawing wants a
// hole, a socket or a crack darker than any lit face.
//   .  empty      1  shadow       3  energy - the active, lit thing
//   0  outline    2  structure    4  pale accent
//
// Every tone but the pale accent is derived from the offer's `theme` colour, so
// one drawing works for any passive item and the game's "colour tells you what
// it does" language stays load-bearing. The steps are further apart than they
// look: the game tone-maps with ACES (main.js), which pulls flat unlit colour
// toward the middle, so an authored ramp has to start wide to survive it.
export function pixelPalette(color) {
  const base = new THREE.Color(color);
  const hsl = { h: 0, s: 0, l: 0 };
  base.getHSL(hsl);
  const tone = (s, l) => new THREE.Color().setHSL(hsl.h, s, l);
  return {
    '0': tone(hsl.s * 0.5, 0.045),   // outline: near-black, faintly tinted
    '1': tone(hsl.s * 0.95, 0.18),   // shadow: the lower-right edge of a form
    '2': tone(hsl.s * 1.0, 0.34),    // structure: the object itself
    '3': tone(Math.min(1, hsl.s * 1.15), 0.62), // energy: what it does
    '4': tone(hsl.s * 0.32, 0.87),   // pale: specular, a few pixels per icon
    side: tone(hsl.s * 0.8, 0.11),   // the extrusion walls
  };
}

// ---- non-item drawings ---------------------------------------------------
//
// GENERATED by tools/pixelart/build.py - see the note at the top of the file.
// 24 strings of 24 characters, top row first, silhouette only: the outline is
// added at load, so no icon ever spends a pixel on it.

const PIXEL_ICONS = {
  // AMMO STATION.
  ammoBox: [
    '........................',
    '........4442.4442.......',
    '........4332.4332.......',
    '........4332.4332.......',
    '........2332.2332.......',
    '.........432..432.......',
    '..22222222322223222221..',
    '..22222222222222222221..',
    '..22222222222222222221..',
    '..12222222222222222211..',
    '...222222222222222221...',
    '...222222222222222221...',
    '...433333333333333332...',
    '...433333333333333332...',
    '...433333333333333332...',
    '...222222222222222221...',
    '...222222222222222221...',
    '...222222222222222221...',
    '...222222222222222221...',
    '...222222222222222221...',
    '...111111111111111111...',
    '........................',
    '........................',
    '........................',
  ],
  // REROLL STATIONS.
  gear: [
    '........................',
    '........................',
    '........................',
    '...........21...........',
    '........22222221........',
    '......222211122221......',
    '.....222111..112221.....',
    '.....2211......1221.....',
    '....1111........1111.2..',
    '...................442..',
    '.................44422..',
    '...............244332...',
    '2...............22332...',
    '442...............222...',
    '43342...............2...',
    '43322421........2211....',
    '4222.2221......2221.....',
    '22...122221..222211.....',
    '......112222222111......',
    '........11121111........',
    '...........11...........',
    '........................',
    '........................',
    '........................',
  ],
  // WEAPON OFFER.
  gun: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '...........221..........',
    '...........221..........',
    '....222222222221........',
    '2222222222222221.....42.',
    '22222223332222222222242.',
    '22222223332222211111132.',
    '2222222222222221.....22.',
    '2222222222222221........',
    '1111111122211111........',
    '........2221............',
    '........2221...1........',
    '........22222211........',
    '........2221111.........',
    '........1111............',
    '........................',
    '........................',
    '........................',
  ],
  // AMMO PICKUP - one magazine off a body.
  pickAmmo: [
    '........................',
    '........................',
    '..........22221.........',
    '..........22221.........',
    '..........22221.........',
    '..........22221.........',
    '.......22222222221......',
    '.......22222222221......',
    '.......22333333321......',
    '.......22333333321......',
    '.......22333333321......',
    '.......22222222221......',
    '.......22333333321......',
    '.......22333333321......',
    '.......22333333321......',
    '.......22222222221......',
    '.......22222222221......',
    '.......22222222221......',
    '.......22222222221......',
    '.......43333333332......',
    '.......43333333332......',
    '.......22222222222......',
    '........................',
    '........................',
  ],
  // HEALTH PICKUP - a cross.
  pickHealth: [
    '........................',
    '........................',
    '........................',
    '.........2222221........',
    '.........2222221........',
    '.........2233321........',
    '.........2233321........',
    '.........2233321........',
    '.........2233321........',
    '...2222222233322222221..',
    '...2222222233322222221..',
    '...2233333333333333321..',
    '...2233333333333333321..',
    '...2233333333333333321..',
    '...2222222233322222221..',
    '...1111112233321111111..',
    '.........2233321........',
    '.........2233321........',
    '.........2233321........',
    '.........2233321........',
    '.........2222221........',
    '.........1111111........',
    '........................',
    '........................',
  ],
  // RAGE PICKUP - damage and speed. A fist.
  pickDamage: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '.....2222222221.........',
    '....222222222221........',
    '....222222222221........',
    '....122222222221........',
    '.....22222222221........',
    '.....222222222222221....',
    '.....233333333332221....',
    '.....233333333332221....',
    '.....222222222222221....',
    '.....222222222211111....',
    '.....22222222221........',
    '.....11222222221........',
    '.......222222221........',
    '.......433333332........',
    '.......433333332........',
    '.......222222222........',
    '........................',
    '........................',
  ],
  // FIRE RATE PICKUP - a bolt.
  pickRate: [
    '........................',
    '.............21.........',
    '.............21.........',
    '............211.........',
    '...........222..........',
    '...........231..........',
    '..........2421..........',
    '.........2232...........',
    '........22332...........',
    '........22331...........',
    '.......22333222211......',
    '......22222233311.......',
    '.....11111223331........',
    '..........223311........',
    '..........23311.........',
    '..........2311..........',
    '..........221...........',
    '..........21............',
    '.........211............',
    '.........11.............',
    '.........1..............',
    '........................',
    '........................',
    '........................',
  ],
  // SHIELD PICKUP.
  pickShield: [
    '........................',
    '........................',
    '..........2221..........',
    '.......2222222221.......',
    '.....22222222222221.....',
    '..2222222222222222221...',
    '..2222222233332222221...',
    '..2222233333333332221...',
    '..2223333333333333221...',
    '..2223333332233333221...',
    '..2223332222222333221...',
    '..2223332222222333221...',
    '..1223332222222333221...',
    '...122233322223332211...',
    '....1222333223332211....',
    '.....12223333332211.....',
    '......122233332211......',
    '.......1222332211.......',
    '........12222211........',
    '.........122211.........',
    '..........1211..........',
    '...........11...........',
    '........................',
    '........................',
  ],
  // MAGNET PICKUP - every orb on the floor comes to you.
  pickMagnet: [
    '........................',
    '........................',
    '..........4442..........',
    '.........443332.........',
    '.........433332.........',
    '.........233322.........',
    '..........2322..........',
    '...........22...........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '....221..........221....',
    '....2221.........2221...',
    '....2221........22221...',
    '....2221........22221...',
    '....22221......222221...',
    '....43332222222223332...',
    '....43332222222223332...',
    '....22221222221112222...',
    '.........111111.........',
    '........................',
    '........................',
  ],
  // BATTERY PICKUP - the active item's meter, filled. A cell with the charge still in it, and the bolt is what the plate promises.
  pickBattery: [
    '........................',
    '........................',
    '.........22222..........',
    '.........22222..........',
    '......2222222222........',
    '......2222222222.1......',
    '......22222222221.......',
    '......223333322221......',
    '......2233333322221.....',
    '......2223333322221.....',
    '......2222333222221.....',
    '......2222333322221.....',
    '......2222233332221.....',
    '......2222233333221.....',
    '......2222223333221.....',
    '......2222233322221.....',
    '......2222333222221.....',
    '......2223332222221.....',
    '......2233322222221.....',
    '......2233222222221.....',
    '......2222222222221.....',
    '......1111111111111.....',
    '........................',
    '........................',
  ],
  // BURNING - a status on the PLAYER. Damage over time.
  statusFire: [
    '........................',
    '...........1............',
    '..........221...........',
    '..........2221..........',
    '.........222221.........',
    '........22222221........',
    '........222222221.......',
    '.......22222222221......',
    '.......22223222221......',
    '.......22233222211......',
    '......22223332211.......',
    '.....22223333321........',
    '.....22223333321........',
    '....2222233333221.......',
    '...222223333322221......',
    '...2222233333222221.....',
    '...22223333333222221....',
    '..2222233333333222221...',
    '..22222333333333222221..',
    '..22222333333333222221..',
    '..12222333333333222211..',
    '...111222333332221111...',
    '......222223222221......',
    '......111111111111......',
  ],
  // POISONED - a status on the player. Damage over time.
  statusPoison: [
    '........................',
    '........................',
    '........................',
    '.................442....',
    '....4442........2432....',
    '....4332...21....222....',
    '...243322..21.....2.....',
    '....4332..2221..........',
    '....2222..2221..........',
    '.........222221.........',
    '........22222221........',
    '.......2222222221.......',
    '......222223322221......',
    '......222333333221......',
    '.....22223333332221.....',
    '.....22223333332221.....',
    '.....12223333332211.....',
    '......222333333221......',
    '......122233332211......',
    '.......1222222211.......',
    '........12222211........',
    '.........111111.........',
    '........................',
    '........................',
  ],
  // AFRAID - a status on the player. The trigger does nothing.
  statusFear: [
    '........................',
    '........................',
    '........................',
    '.........222221.........',
    '.......2222222221.......',
    '......222222222221......',
    '......222222222221......',
    '.....22333222233321.....',
    '.....23333322333331.....',
    '....2233333223333321....',
    '....2233333223333321....',
    '....2223332222333221....',
    '....2222222222222221....',
    '....2222222002222221....',
    '....2222220000222221....',
    '....1222200000022211....',
    '.....22220000002221.....',
    '.....12220000002211.....',
    '......122000000211......',
    '.......1220000211.......',
    '........12200211........',
    '.........111111.........',
    '........................',
    '........................',
  ],
  // WEAKENED - a status on the player. Your shots hit softer.
  statusWeakness: [
    '........................',
    '........................',
    '...2222221......442.....',
    '...2222221......432.....',
    '...2222221......432.....',
    '...2222221......432.....',
    '...2222221......432.....',
    '...2222221......432.....',
    '...2222221......432.....',
    '...2222221......432.....',
    '...2222221......432.....',
    '...1111111......432.....',
    '................432.....',
    '.....2222221....432.....',
    '.....2222221.24443342...',
    '.....2222221..2333322...',
    '.....2222221...43332....',
    '.....2222211...23322....',
    '.....122221.....422.....',
    '......22221.....22......',
    '......12211......2......',
    '.......111..............',
    '........1...............',
    '........................',
  ],
  // CURSED - a status on the player. Everything hurts 25% more.
  statusCurse: [
    '........................',
    '........................',
    '........................',
    '..1..................1..',
    '...1................1...',
    '...21..............21...',
    '...221............221...',
    '...1211..222221..1211...',
    '....11.2222222221.11....',
    '......222111112221......',
    '.....22221....22221.....',
    '.....22333444443321.....',
    '....2211333333321221....',
    '....221.23333322.221....',
    '....221..433332..221....',
    '....221..233322..221....',
    '....1221..2322..2211....',
    '.....221...42...221.....',
    '.....1221..42..2211.....',
    '......122222222211......',
    '.......1222222211.......',
    '........11111111........',
    '........................',
    '........................',
  ],
  // SLOWED - a status on the player. You move at a fraction.
  statusSlowness: [
    '........................',
    '........................',
    '..222222222222222222221.',
    '..222222222222222222221.',
    '..222222222222222222221.',
    '..131112333322221113111.',
    '...41..2333322221..41...',
    '...21..2233322221..11...',
    '...11..1233322211.......',
    '........23332221........',
    '........23332221........',
    '........12332211........',
    '.........233221.........',
    '.........233221.........',
    '.........123211.........',
    '..........2321..........',
    '..........2321..........',
    '..........1311..........',
    '...........21...........',
    '...........11...........',
    '............1...........',
    '........................',
    '........................',
    '........................',
  ],
};

// Each key has one owner. Reject a collision rather than silently taking the
// last drawing, which could make two unrelated offers wear the same art.
const iconRows = new Map(Object.entries(PIXEL_ICONS));
const iconOwners = new Map([...iconRows.keys()].map((key) => [key, 'non-item catalogue']));
for (const [owner, icons] of [
  ['passive item', PASSIVE_ITEM_ICONS],
  ['active item', ACTIVE_ITEM_ICONS],
  ['donation item', DONATION_ITEM_ICONS],
]) {
  for (const [key, rows] of Object.entries(icons)) {
    if (iconOwners.has(key)) {
      throw new Error(`duplicate pixel icon ${key}: ${iconOwners.get(key)} and ${owner}`);
    }
    iconOwners.set(key, owner);
    iconRows.set(key, rows);
  }
}

const ICON_ROW = /^[.01234]{24}$/;
for (const [key, rows] of iconRows) {
  if (!Array.isArray(rows) || rows.length !== GRID
      || rows.some((row) => typeof row !== 'string' || !ICON_ROW.test(row))) {
    throw new Error(`malformed pixel icon: ${key}`);
  }
}

export const PIXEL_ICON_KEYS = [...iconRows.keys()];

/**
 * Reads an authored map and adds the generated outline.
 * @returns {string[][]} GRID rows of GRID tone characters, '.' for empty
 */
export function resolveIcon(key) {
  const src = iconRows.get(key);
  if (!src) throw new Error('no pixel icon: ' + key);
  const cells = src.map(row => row.split(''));
  return addOutline(cells);
}

/**
 * Adds the generated one-cell outline to a tone grid.
 *
 * Eight-neighbour, so a diagonal step gets its corner pixel and the outline
 * never breaks. A four-neighbour ring leaves a gap on every 45deg edge.
 *
 * SHARED, NOT COPIED. This is the same dilation every icon gets, and the
 * floor shapes in effects.js call it too. That is the whole reason it is a
 * function: "the creep belongs to the same set as the icons" should be a fact
 * about the code, not a claim about the art.
 *
 * @param {string[][]} cells  square grid of tone characters, '.' for empty
 * @param {boolean} pad  grow the result by one cell on every side, so a shape
 *   that touches the edge still gets a complete border. Icons never need this
 *   - they are authored with a margin - but a rasterised patch fills its grid.
 * @returns {string[][]} a new grid; the input is not modified
 */
export function addOutline(cells, pad = false) {
  const n = cells.length;
  const m = pad ? n + 2 : n;
  const o = pad ? 1 : 0;
  const src = (y, x) => {
    const sy = y - o, sx = x - o;
    return sy < 0 || sy >= n || sx < 0 || sx >= n ? '.' : cells[sy][sx];
  };
  const out = [];
  for (let y = 0; y < m; y++) {
    const row = new Array(m);
    for (let x = 0; x < m; x++) {
      const here = src(y, x);
      if (here !== '.') { row[x] = here; continue; }
      let touches = false;
      for (let dy = -1; dy <= 1 && !touches; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          if (src(y + dy, x + dx) !== '.') { touches = true; break; }
        }
      }
      row[x] = touches ? '0' : '.';
    }
    out.push(row);
  }
  return out;
}

// ---- rasterising a shape onto the grid -----------------------------------
//
// Item icons are authored as grids beside their definitions, and non-item art
// is drawn in tools/pixelart. The floor shapes cannot be authored as grids:
// there are eight creep variants, and their outlines have to keep agreeing
// with the damage circle the gameplay uses. So they are rasterised from the
// same maths that used to emit a polygon - the drawing is generated, but it
// lands on the same grid, gets the same light and the same outline, and comes
// out looking like it was drawn by whoever drew the icons.

/**
 * Fills a grid from a shape predicate.
 * @param {(u:number,v:number)=>boolean} inside  tested at each cell centre in
 *   -1..1 space, y DOWN to match the icon rows
 * @param {number} n  grid size
 * @param {string} tone  what a filled cell starts as
 */
export function rasterize(inside, n, tone = '2') {
  const out = [];
  for (let y = 0; y < n; y++) {
    const row = new Array(n);
    for (let x = 0; x < n; x++) {
      const u = ((x + 0.5) / n) * 2 - 1;
      const v = ((y + 0.5) / n) * 2 - 1;
      row[x] = inside(u, v) ? tone : '.';
    }
    out.push(row);
  }
  return out;
}

/**
 * The shared lighting pass, in JS. The twin of shade() in
 * tools/pixelart/canvas.py, and it has to stay the twin: light from the upper
 * left, on every icon and every floor shape, without exception. A `base` cell
 * on the silhouette's lower-right edge becomes shadow; one on its upper-left
 * edge becomes the pale accent. Edges are measured against the WHOLE
 * silhouette, so a part tucked behind another part is not lit as though it
 * were out in the open.
 *
 * Mutates and returns `cells`.
 */
export function shadeGrid(cells, base = '2', shadow = '1', light = '4') {
  const n = cells.length;
  const src = cells.map(r => r.slice());
  const out = (x, y) => x < 0 || x >= n || y < 0 || y >= n || src[y][x] === '.';
  for (let y = 0; y < n; y++) {
    for (let x = 0; x < n; x++) {
      if (src[y][x] !== base) continue;
      if (out(x + 1, y) || out(x, y + 1) || out(x + 1, y + 1)) cells[y][x] = shadow;
      else if (light && (out(x - 1, y) || out(x, y - 1) || out(x - 1, y - 1))) cells[y][x] = light;
    }
  }
  return cells;
}

/**
 * Chebyshev distance from every filled cell to the nearest empty one, by
 * repeated erosion. Used to find a shape's core: a patch is structure at the
 * rim and energy in the middle, which is how the icons read, without anyone
 * having to author where the middle is.
 */
export function erodeDepth(cells) {
  const n = cells.length;
  const d = cells.map(r => r.map(c => (c === '.' ? 0 : Infinity)));
  const at = (y, x) => (y < 0 || y >= n || x < 0 || x >= n ? 0 : d[y][x]);
  // Two sweeps of the chamfer transform - forward then backward - is exact for
  // the 8-neighbour metric and costs two passes instead of one per ring.
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
    if (d[y][x] === 0) continue;
    d[y][x] = Math.min(d[y][x], 1 + Math.min(at(y - 1, x - 1), at(y - 1, x), at(y - 1, x + 1), at(y, x - 1)));
  }
  for (let y = n - 1; y >= 0; y--) for (let x = n - 1; x >= 0; x--) {
    if (d[y][x] === 0) continue;
    d[y][x] = Math.min(d[y][x], 1 + Math.min(at(y + 1, x + 1), at(y + 1, x), at(y + 1, x - 1), at(y, x + 1)));
  }
  return d;
}

// ---- flat grid plates ----------------------------------------------------
//
// The 2D half of buildPixelIcon: one merged quad per filled cell, no
// extrusion, no side walls, meant to lie on the floor.
//
// THE TONE IS AN ATTRIBUTE AND THE COLOUR IS A UNIFORM, which is the opposite
// of the icons and is the only reason this is a separate builder. An icon is
// built once per (key, colour) and cached; a creep patch is recoloured every
// frame by whatever zone borrowed it out of the pool. Baking tones into vertex
// colours would force a geometry copy per pool slot - thirty of them - and the
// smoke test holds the whole game to under 120 geometries.

/**
 * @param {string[][]} cells  tone grid, row 0 at the TOP
 * @param {number} cell  edge length of one art-pixel, in local units
 * @returns {THREE.BufferGeometry} centred on the origin, in the XY plane
 */
export function gridPlate(cells, cell) {
  const n = cells.length;
  const half = (n * cell) / 2;
  const pos = [];
  const tone = [];
  const TONES = { '0': 0, '1': 1, '2': 2, '3': 3, '4': 4 };
  for (let y = 0; y < n; y++) {
    for (let x = 0; x < n; x++) {
      const t = TONES[cells[y][x]];
      if (t === undefined) continue;
      const x0 = x * cell - half, x1 = x0 + cell;
      // Row 0 is the top row, so y counts DOWN from +half.
      const y1 = half - y * cell, y0 = y1 - cell;
      pos.push(x0, y0, 0, x1, y0, 0, x1, y1, 0, x0, y0, 0, x1, y1, 0, x0, y1, 0);
      for (let i = 0; i < 6; i++) tone.push(t);
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('aTone', new THREE.Float32BufferAttribute(tone, 1));
  return g;
}

// The GLSL twin of pixelPalette(). It has to be a twin rather than a lookup
// table handed in as uniforms because that is five vec3s per pool slot to keep
// in sync by hand; here the ramp exists once, in one place, in two languages
// that can be read side by side.
// The ramp itself, as GLSL, with no uniforms and no main(). Split out from the
// plate material below because the creep FIELD needs the same five tones from
// a hue it reads per-texel rather than from a uniform, and two copies of a
// colour ramp is exactly the drift this whole module exists to prevent.
export const PALETTE_RAMP_GLSL = /* glsl */ `
  float hue2rgb(float p, float q, float t) {
    if (t < 0.0) t += 1.0;
    if (t > 1.0) t -= 1.0;
    if (t < 1.0 / 6.0) return p + (q - p) * 6.0 * t;
    if (t < 1.0 / 2.0) return q;
    if (t < 2.0 / 3.0) return p + (q - p) * 6.0 * (2.0 / 3.0 - t);
    return p;
  }

  vec3 hsl(float h, float s, float l) {
    if (s <= 0.0) return vec3(l);
    float q = l < 0.5 ? l * (1.0 + s) : l + s - l * s;
    float p = 2.0 * l - q;
    return vec3(hue2rgb(p, q, h + 1.0 / 3.0), hue2rgb(p, q, h), hue2rgb(p, q, h - 1.0 / 3.0));
  }

  // tone 0..4, and the same five steps pixelPalette() returns in JS.
  vec3 paletteTone(float tone, float h, float s) {
    float sat, lum;
    if (tone < 0.5)      { sat = s * 0.5;              lum = 0.045; }
    else if (tone < 1.5) { sat = s * 0.95;             lum = 0.18;  }
    else if (tone < 2.5) { sat = s;                    lum = 0.34;  }
    else if (tone < 3.5) { sat = min(1.0, s * 1.15);   lum = 0.62;  }
    else                 { sat = s * 0.32;             lum = 0.87;  }
    return hsl(h, sat, lum);
  }
`;

const PALETTE_GLSL = PALETTE_RAMP_GLSL + /* glsl */ `
  uniform vec3 uHSL;
  uniform float uOpacity;
  varying float vTone;

  void main() {
    gl_FragColor = vec4(paletteTone(vTone, uHSL.x, uHSL.y), uOpacity);
    #include <tonemapping_fragment>
  }
`;

const PLATE_VERT = /* glsl */ `
  attribute float aTone;
  varying float vTone;
  void main() {
    vTone = aTone;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

/**
 * A material for gridPlate() geometry. One per pool slot - they differ only in
 * their uniforms, so three.js compiles the program once and reuses it.
 *
 * NORMAL BLENDING, NOT ADDITIVE, and that is the visible half of this whole
 * change. Additive was what made the old creep look like a vector VFX blob: it
 * cannot draw anything darker than the floor, so the generated outline - the
 * single feature that ties the shape to the icons - would add zero and vanish.
 * A patch is a piece of floor that has been PAINTED, so it paints.
 */
export function gridMaterial(color = 0xffffff, opacity = 1) {
  const hsl = { h: 0, s: 0, l: 0 };
  new THREE.Color(color).getHSL(hsl);
  return new THREE.ShaderMaterial({
    uniforms: {
      uHSL: { value: new THREE.Vector3(hsl.h, hsl.s, hsl.l) },
      uOpacity: { value: opacity },
    },
    vertexShader: PLATE_VERT,
    fragmentShader: PALETTE_GLSL,
    transparent: true,
    depthWrite: false,
    side: THREE.DoubleSide,
  });
}

/** Writes a hex colour into a gridMaterial's uniforms. */
const _hsl = { h: 0, s: 0, l: 0 };
const _col = new THREE.Color();
export function gridTint(mat, color) {
  _col.setHex(color).getHSL(_hsl);
  mat.uniforms.uHSL.value.set(_hsl.h, _hsl.s, _hsl.l);
}

// ---- geometry ------------------------------------------------------------
//
// One merged, non-indexed, vertex-coloured BufferGeometry per icon, so the
// whole thing is a single draw call however many pixels it has. Interior faces
// between neighbouring pixels are never emitted - only the front, the back and
// whatever side walls are actually exposed - which is why a 200-pixel icon
// costs a few hundred triangles rather than 200 boxes.
//
// UNLIT ON PURPOSE. MeshBasicMaterial, no lights, no shading: the moment a
// light rakes across the face it stops being flat art. The shading is painted
// into the tones, and the only thing that gives the object away as solid is
// the darker colour on the side walls.

function quad(pos, col, a, b, c, d, color) {
  for (const v of [a, b, c, a, c, d]) pos.push(v[0], v[1], v[2]);
  for (let i = 0; i < 6; i++) col.push(color.r, color.g, color.b);
}

// Geometry is cached by (icon, colour) and shared. The tones are baked into a
// vertex attribute rather than a uniform - four of the five are derived from
// the theme with different saturations, so they are not one hue times one
// number and cannot be collapsed into a material colour - which means the
// buffer does depend on the colour. Without this cache each of the three
// totems would build its own copy of every offer it ever showed, and the
// geometry count would grow with totems x pool instead of with the pool.
const geoCache = new Map();

function iconGeometry(key, color) {
  const ck = key + '|' + color;
  let g = geoCache.get(ck);
  if (g) return g;
  const cells = resolveIcon(key);
  const pal = pixelPalette(color);
  const pos = [];
  const col = [];
  const half = GRID / 2;
  const zf = DEPTH / 2;
  const zb = -DEPTH / 2;
  const filled = (x, y) => x >= 0 && x < GRID && y >= 0 && y < GRID && cells[y][x] !== '.';

  for (let y = 0; y < GRID; y++) {
    for (let x = 0; x < GRID; x++) {
      const t = cells[y][x];
      if (t === '.') continue;
      const x0 = (x - half) * PX;
      const x1 = x0 + PX;
      // Row 0 is the TOP row, so y runs down the grid and up the world.
      const y1 = (half - y) * PX;
      const y0 = y1 - PX;
      const face = pal[t];
      const side = pal.side;
      // The face. This is the art; everything else is the slab it sits on.
      quad(pos, col, [x0, y0, zf], [x1, y0, zf], [x1, y1, zf], [x0, y1, zf], face);
      // The back, seen only as the icon swings past - kept dark so it never
      // competes with the front.
      quad(pos, col, [x1, y0, zb], [x0, y0, zb], [x0, y1, zb], [x1, y1, zb], side);
      if (!filled(x - 1, y)) quad(pos, col, [x0, y0, zb], [x0, y0, zf], [x0, y1, zf], [x0, y1, zb], side);
      if (!filled(x + 1, y)) quad(pos, col, [x1, y0, zf], [x1, y0, zb], [x1, y1, zb], [x1, y1, zf], side);
      if (!filled(x, y - 1)) quad(pos, col, [x0, y1, zf], [x1, y1, zf], [x1, y1, zb], [x0, y1, zb], side);
      if (!filled(x, y + 1)) quad(pos, col, [x0, y0, zb], [x1, y0, zb], [x1, y0, zf], [x0, y0, zf], side);
    }
  }

  g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3));
  g.computeBoundingSphere();
  geoCache.set(ck, g);
  return g;
}

/**
 * Builds one pixel icon. The caller owns the returned group and should keep
 * it; the geometry inside is shared, but the material is not - it carries the
 * pulse, so every icon needs its own.
 *
 * @param {string} key    an entry in PIXEL_ICON_KEYS
 * @param {number} color  the offer's theme colour
 * @returns {THREE.Group}
 */
/**
 * The same drawing, rendered flat for the DOM.
 *
 * The HUD's buff chips wear the icons the pickups wear - one drawing, two
 * renderers - so a red chip in the corner and the red thing that was picked up
 * off the floor are visibly the same object. Returns a canvas at GRID*scale
 * pixels; the caller sizes it with CSS and sets image-rendering: pixelated.
 *
 * Built once per chip and never per frame: this walks 576 cells.
 */
export function pixelIconCanvas(key, color, scale = 2) {
  const cells = resolveIcon(key);
  const pal = pixelPalette(color);
  const cv = document.createElement('canvas');
  cv.width = GRID * scale;
  cv.height = GRID * scale;
  const g = cv.getContext('2d');
  const css = new Map();
  for (const k of Object.keys(pal)) css.set(k, '#' + pal[k].getHexString());
  for (let y = 0; y < GRID; y++) {
    for (let x = 0; x < GRID; x++) {
      const t = cells[y][x];
      if (t === '.') continue;
      g.fillStyle = css.get(t) || '#fff';
      g.fillRect(x * scale, y * scale, scale, scale);
    }
  }
  return cv;
}

export function buildPixelIcon(key, color) {
  const mat = new THREE.MeshBasicMaterial({ vertexColors: true });
  const group = new THREE.Group();
  group.add(new THREE.Mesh(iconGeometry(key, color), mat));

  // totems.js pulses `icon.userData.glow.emissiveIntensity` every frame. There
  // is no emissive here - the material is unlit - so the same write is taken as
  // a brightness multiplier on the whole plate instead. Standing in for the old
  // interface rather than changing the caller keeps this a drop-in: nothing
  // outside this file has to know which catalogue built the icon.
  group.userData.glow = {
    set emissiveIntensity(v) {
      mat.color.setScalar(Math.min(1.6, 0.55 + v * 0.33));
    },
    get emissiveIntensity() { return 1; },
  };
  return group;
}
