"""Draws every icon and rewrites the PIXEL_ICONS table in js/pixelicons.js."""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from canvas import Canvas
import icons as A

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
TARGET = os.path.join(ROOT, 'js', 'pixelicons.js')

# One line per icon saying what the passive item does, so the table reads as a
# design document rather than as 1,560 characters of noise.
NOTE = {
    'overclock': 'OVERCLOCK - fire rate. A dial with the needle past the stop.',
    'extendedMag': 'EXTENDED MAG - magazine size. The rounds show through it.',
    'speedLoader': 'SPEED LOADER - reload speed. A cylinder charged all at once.',
    'beltFeed': 'BELT FEED - some shots come straight off the reserve.',
    'ammoHoarder': 'AMMO HOARDER - twice the reserve. The biggest drum there is.',
    'ammoFab': 'AMMO FABRICATOR - rounds made out of nothing, per second.',
    'scavenger': 'SCAVENGER - kills pull ammo to you.',
    'lodestone': 'LODESTONE - money and pickups come to you. The coin pulls.',
    'ammoBox': 'AMMO STATION.',
    'pickAmmo': 'AMMO PICKUP - one magazine off a body.',
    'pickHealth': 'HEALTH PICKUP - a cross.',
    'pickDamage': 'RAGE PICKUP - damage and speed. A fist.',
    'pickRate': 'FIRE RATE PICKUP - a bolt.',
    'pickShield': 'SHIELD PICKUP.',
    'pickBattery': "BATTERY PICKUP - the active item's meter, filled. A cell with the"
                   ' charge still in it, and the bolt is what the plate promises.',
    'pickMagnet': 'MAGNET PICKUP - every orb on the floor comes to you.',
    'hollowPoint': 'HOLLOW POINT - more damage, smaller magazine. Nose-on.',
    'steadyAim': 'STEADY AIM - damage while you do not move. Planted.',
    'glassCannon': 'GLASS CANNON - all damage, no health. Already cracked.',
    'tripleTap': 'TRIPLE TAP - three rounds spent on one shot.',
    'darkPower': 'DARK POWER - damage for nothing. Appetite, not a weapon.',
    'berserker': 'BERSERKER - the emptier the heart, the harder you hit.',
    'hotStreak': 'HOT STREAK - damage climbs while you keep hitting.',
    'noHitBonus': 'NO-HIT BONUS - a wave cleared without being touched.',
    'cursedAmmo': 'CURSED AMMO - a round that costs you health to fire.',
    'devilsGamble': "DEVIL'S GAMBLE - every shot is a coin toss.",
    'midas': 'MIDAS TOUCH - the dead turn gold.',
    'executioner': 'EXECUTIONER - bosses lose half their health.',
    'holyMantle': 'HOLY MANTLE - the first three hits of a wave pass through you.',
    'deadCat': 'DEAD CAT - one more life, and less of it.',
    'bulwark': 'BULWARK - health bought with speed.',
    'nanoweave': 'NANOWEAVE - health that comes back on its own.',
    'reactivePlating': 'REACTIVE PLATING - being hit sets off a shockwave.',
    'vampiric': 'VAMPIRIC ROUNDS - kills give health back.',
    'bloodPact': 'BLOOD PACT - kills heal, everything else hurts more.',
    'combatStims': 'COMBAT STIMS - move faster.',
    'thorns': 'THORNS - whoever hits you gets all of it back.',
    'evasion': 'EVASION - some hits simply find nobody there.',
    'doubleJump': 'DOUBLE JUMP - a second jump with no ground under it.',
    'venom': 'VENOM ROUNDS - the ammunition is poisoned, not the enemy.',
    'incendiary': 'INCENDIARY - hits set fire and it spreads off the dead.',
    'cryo': 'CRYO ROUNDS - hits halve their speed, and their shots too.',
    'petrify': 'PETRIFY - a chance to stop something where it stands.',
    'terror': 'TERROR - hit enemies run, and cannot shoot while they do.',
    'knockout': 'KNOCKOUT DROPS - hits shove.',
    'arcRounds': 'ARC ROUNDS - a hit jumps to one more enemy.',
    'piercingShot': 'PIERCING SHOT - one shot, several enemies.',
    'gravityRounds': 'GRAVITY ROUNDS - hits pull everything nearby inward.',
    'twentyTwenty': 'TWENTY/TWENTY - one trigger pull, two rounds.',
    'seeker': 'SEEKER - a miss bends onto the target anyway.',
    'detonator': 'DETONATOR - hits explode.',
    'breachRound': 'BREACH ROUND - the first shot after a reload goes off.',
    'reloadBurst': 'RELOAD BURST - the reload itself is the attack.',
    'neurotoxin': 'NEUROTOXIN - poison moves between bodies.',
    'malady': 'MALADY - poison and fire burn hotter and shorter.',
    'entropy': 'ENTROPY - the timer breaks and the status stays.',
    'crystallize': 'CRYSTALLIZE - the frozen dead come apart.',
    'ashen': 'ASHEN - the burnt dead leave something still burning.',
    'blastCorpse': 'BLAST CORPSE - the dead go off, and not only at enemies.',
    'eternalAffliction': 'ETERNAL AFFLICTION - it never lifts.',
    'absoluteZero': 'ABSOLUTE ZERO - the whole arena slows, you included.',
    'antidote': 'ANTIDOTE - poison in the world heals you instead.',
    'hellfire': 'HELLFIRE - a reload lays fire on the ground behind you.',
    'overload': 'OVERLOAD - an empty magazine discharges into everything.',
    'lightningWizard': 'LIGHTNING WIZARD - hits call it down from above.',
    'carnage': 'CARNAGE - damage stacked on kills, lost the moment you are hurt.',
    'statusFire': 'BURNING - a status on the PLAYER. Damage over time.',
    'statusPoison': 'POISONED - a status on the player. Damage over time.',
    'statusFear': 'AFRAID - a status on the player. The trigger does nothing.',
    'statusWeakness': 'WEAKENED - a status on the player. Your shots hit softer.',
    'statusCurse': 'CURSED - a status on the player. Everything hurts 25% more.',
    'statusSlowness': 'SLOWED - a status on the player. You move at a fraction.',
    'hairTrigger': 'HAIR TRIGGER - rate bought with recoil. The trigger and the kick.',
    'brassEcho': 'BRASS ECHO - a round that hit comes back to the reserve.',
    'openingSalvo': 'OPENING SALVO - the first ten seconds of a wave are free.',
    'untouched': 'UNTOUCHED - max HP banked for every wave nothing touched you.',
    'scarTissue': 'SCAR TISSUE - max HP every wave, and every hit hurts more.',
    'blackout': 'BLACKOUT - health bought with the range you can see.',
    'digIn': 'DIG IN - stand still and you knit back together.',
    'secondWind': 'SECOND WIND - stamina spent slower and returned faster.',
    'gear': 'REROLL STATIONS.',
    'gun': 'WEAPON OFFER.',
    'itemHeal': 'TRAUMA KIT - heal 25 HP. A case, so it is not pickHealth.',
    'itemFreeze': 'CRYO PULSE - freeze the room. A flake inside a shockwave.',
    'itemRage': 'OVERDRIVE - 2x damage. A governor pushed past its stop.',
    'itemGuard': 'AEGIS - invincible. A dome, not a shield in a hand.',
    'itemDash': 'BLINK DRIVE - the dash, now a device in a slot.',
    'itemPurify': 'WHITE CELL - clear every affliction. A cell eating the dark.',
    'itemInferno': 'BRIMSTONE - the whole room burns. Fire over a crowd.',
    'itemArc': "JACOB'S LADDER - a bolt walks through five bodies.",
    'itemMercy': 'LAST RITES - the nearly dead are finished. Skull and flatline.',
    'itemLeech': 'HAEMOPHAGE - hits heal. A leech coiled round the round.',
    'itemLastStand': 'WATERLINE - healed up to half, and no further.',
    'itemQuake': 'TECTONIC - the ground drives them all outward.',
    'itemRate': 'RED LINE - the dial with the needle in the red block.',
    'itemFrenzy': 'RED MIST - three times damage, twice taken. An open jaw.',
    'itemTally': 'BODY COUNT - damage per kill. A five bar gate.',
    'itemPact': 'BLOOD TAX - health for damage. An opened palm.',
    'itemRoulette': 'SIX CHAMBERS - one chamber loaded out of six.',
    'itemDonate': 'OPEN VEIN - blood into ammunition. A bag feeding a magazine.',
    'itemRegen': 'SUTURE ENGINE - health knitted back. Needle and stitches.',
    'itemReroll': 'SECOND OPINION - two free rerolls. A coin nobody paid for.',
    'itemHumours': 'FOUR HUMOURS - every element in turn. A quartered round.',
    'itemGraft': 'GRAFT - permanent max health. A heart with a patch on it.',
    'itemMartyr': 'MARTYR - you are the bomb. A figure inside the blast.',
    'itemMeteor': 'FALLING SKY - rocks, plural, still falling.',
    'itemLodestar': 'LODESTAR - the floor comes to you. Orbs into a star.',
    'itemHoming': 'BIRD DOG - the shot arrives. A curve into a target.',
    'itemBlink': 'COLD SPOT - out here, in over there, nothing between.',
    'itemStone': 'BLOOD FROM STONE - money heals. A drop out of a fracture.',
    'itemBomb': 'SHORT FUSE - three seconds. The fuse is the whole icon.',
    'itemMine': 'WELCOME MAT - a plate with prongs, waiting for a foot.',
    'itemWall': 'FIREBREAK - fire standing in a line, stopping rounds.',
    'itemTurret': 'LITTLE BROTHER - a tripod with one barrel and an eye.',
    'itemSwarm': 'APIARY - five bees leaving one cell.',
    'itemHole': 'EVENT HORIZON - a hole. The darkest centre in the set.',
    'itemBoot': 'BOOTSTRAP - straight up. A boot on a flame.',
    'itemCharge': 'BONESAW - a serrated wedge through what it went through.',
    'itemLance': 'LANCE - thirty rounds as one. The biggest object in the set.',
    'deadeye': 'DEADEYE - crit chance. The only eye in the set.',
    'marksman': 'MARKSMAN - more crit chance. Four brackets round nothing.',
    'deadCenter': 'DEAD CENTER - harder crits, half as many. All bullseye.',
    'assassin': 'ASSASSIN - the first hit on a body. A dagger.',
    'telltale': 'TELLTALE - every third hit on a body. A tally, struck through.',
    'longshot': 'LONGSHOT - damage that grows with range. Drawn going away.',
    'pointBlank': 'POINT BLANK - damage up close. A muzzle flash, no travel.',
    'bloodMoney': 'BLOOD MONEY - paid for being hurt. A coin that bleeds.',
    'adrenaline': 'ADRENALINE - damage per hit taken. A syringe and a ramp.',
    'rabbitsFoot': "RABBIT'S FOOT - things drop more often. A paw on a chain.",
    'crouchfire': 'CROUCHFIRE - fire rate while crouched. A body under a ceiling.',
    'bloodsport': 'BLOODSPORT - melee kills heal. A fist that bleeds.',
    'warChest': 'WAR CHEST - damage per $1,000 held. Money as ammunition.',
    'twinCell': 'TWIN CELL - two item charges. One cell full, one filling.',
    'magpie': 'MAGPIE - a bird that collects credits. The tail is the bird.',
    'lamprey': 'LAMPREY - a leech that guards you. A ring of teeth.',
    'itemCrit': 'SWEET SPOT - every shot crits. A crosshair on a spark.',
    'itemAmmo': 'BANDOLIER - +30 rounds. A belt, where the family has drums.',
    'itemMonkey': 'ORGAN GRINDER - a cymbal monkey. The key says TOY.',
    'fatalReserve': 'FATAL RESERVE - the last five rounds, and only those.',
    'primedMag': 'PRIMED MAG - a magazine with a grenade pin in it.',
    'bailiff': 'BAILIFF - a cell with the arrow coming back into it.',
    'paceCar': 'PACE CAR - a chequered flag, and a full heart at the pole.',
    'ceramicInsert': 'CERAMIC INSERT - a plate with a round stopped dead on it.',
    'overdraw': 'OVERDRAW - a full cross spilling into a cell.',
    'leadBalloon': 'LEAD BALLOON - the name, drawn. A weight on a dead balloon.',
    'cheekweld': 'CHEEKWELD - a stock in profile, the cheekpiece raised.',
    'groundhog': 'GROUNDHOG - a head out of a hole. Safe because it is down there.',
    'itemLockpick': 'LOCKPICK - a padlock with a pick in the keyway.',
    'itemPayToWin': 'PAY TO WIN - a trophy with a dollar struck on the cup.',
    # ---- the second pool ---------------------------------------------------
    'machineSpirit': 'MACHINE SPIRIT - a held trigger climbing. A ramp under a barrel.',
    'overwound': 'OVERWOUND - a mainspring wound past its stop, and the end that let go.',
    'hipshot': 'HIPSHOT - the sights struck out, and the gun firing from the hip.',
    'metronome': 'METRONOME - the object itself. On the beat, or not at all.',
    'echoChamber': 'ECHO CHAMBER - one round and the ghost of it.',
    'cannonade': 'CANNONADE - the first round of a magazine. A cannon, discharging.',
    'heavyHand': 'HEAVY HAND - a sledge. Hits harder, swings slower.',
    'weakPoint': 'WEAK POINT - a plate with a crack through it.',
    'overkill': 'OVERKILL - through the skull and still going.',
    'bloodOath': 'BLOOD OATH - a heart opened on a blade, paying by the wave.',
    'sharedPain': 'SHARED PAIN - one blow arriving, three leaving.',
    'grayMatter': 'GRAY MATTER - a brain, half of it lit and half of it not.',
    'sacrifice': 'SACRIFICE - a blade down through another pick.',
    'bottomFeeder': 'BOTTOM FEEDER - an empty magazine, and what comes out of it.',
    'payday': 'PAYDAY - a bag. The only sack in the set.',
    'ammoSurplus': 'AMMO SURPLUS - a crate that will not shut.',
    'highStakes': 'HIGH STAKES - a coin in the air, edge on. Not resolved yet.',
    'bruiseRounds': 'BRUISE ROUNDS - a magazine loaded with what it cost.',
    'chainFeed': 'CHAIN FEED - a belt with no end.',
    'beltFedDream': 'BELT FED DREAM - the magazine struck out, and the belt instead.',
    'cashCannon': 'CASH CANNON - a muzzle throwing coins.',
    'lastBreath': 'LAST BREATH - lungs, with a round down the windpipe.',
    'autoLoot': 'AUTO-LOOT - a funnel with the floor going into it.',
    'criticalOverflow': 'CRITICAL OVERFLOW - a crit on the ammunition, not on the aim.',
    'ironLung': 'IRON LUNG - a respirator. Nothing gets in.',
    'lifeline': 'LIFELINE - a trace that flatlines and then comes back.',
    'boneMarrow': 'BONE MARROW - a bone cut through. The health is in there.',
    'healthyCore': 'HEALTHY CORE - a cross sealed inside a shell. The only way in.',
    'emergencyRations': 'EMERGENCY RATIONS - a tin, half full. Fifty, drawn.',
    'finalDose': 'FINAL DOSE - the last round, with a cross on the case.',
    'aimOrBleed': 'AIM OR BLEED - a reticle bleeding from one arm.',
    'killStreak': 'KILL STREAK - chevrons climbing to a cross.',
    'vitalTrigger': 'VITAL TRIGGER - the button, with a cross on it.',
    'tireless': 'TIRELESS - the one symbol in the set, over a full bar.',
    'panicTurret': 'PANIC TURRET - a gun inside a warning triangle.',
    'delayedFuse': 'DELAYED FUSE - a clock standing in a blast. The wait is the pick.',
    'fearAura': 'FEAR AURA - rings going out, and something leaving with them.',
    'statusConduit': 'STATUS CONDUIT - a hub wired to three bodies.',
    'trueStrike': 'TRUE STRIKE - a fletched shaft already arrived.',
    'domino': 'DOMINO - the tile. It means "this sets off the next" everywhere.',
    'luckyStreak': 'LUCKY STREAK - a horseshoe, its nail holes climbing one arm.',
    # ---- the third block of active items -----------------------------------
    'itemInsurance': 'LIFE INSURANCE - a heart falling into a safety net.',
    'itemBackorder': 'BACKORDER - a tied parcel. What is in it is not yours yet.',
    'itemMedicalDebt': 'MEDICAL DEBT - an invoice, torn off. A bill means later.',
    'itemLifeSentence': 'LIFE SENTENCE - a ball and chain, and the cuff is shut.',
    'itemCompound': 'COMPOUND INTEREST - a per cent sign. The only notation here.',
    'itemFaith': 'FAITH HEALING - a halo over somebody with their arms open.',
    'itemPickpocket': 'PICKPOCKET - a wallet with somebody else\'s things in it.',
    'itemHeadCount': 'HEAD COUNT - a clipboard. Who is still standing, and what for.',
    'itemExecutive': 'EXECUTIVE DECISION - a gavel. It is over because somebody said.',
    'itemFeltThat': 'EVERYONE FELT THAT - a stock, and the room going out from it.',
    'itemPanic': 'PANIC BUTTON - the button. The one thing here you press.',
    'itemFoodPoisoning': 'FOOD POISONING - a bowl, and what is coming off it.',
    'itemMolotov': 'MOLOTOV - a bottle with a rag in the neck. The only glass here.',
    'itemTransfusion': 'BLOOD TRANSFUSION - two arrows round a drop. Turned into.',
    'itemEncore': 'ENCORE - two notes. The only music in the set.',
    'itemMagDump': 'MAG DUMP - a magazine tipped out. A spill, not a burst.',
    'itemPinata': 'PINATA - a star on a cord, and the stick for it.',
    'itemMoneyShot': 'MONEY SHOT - a coin coming apart. Spent, not banked.',
    'itemLava': 'FLOOR IS LAVA - the floor gone, and one pillar still in it.',
    'itemBalloons': 'PARTY BALLOONS - three, inflated, carrying something up.',
    'itemParachute': 'GOLDEN PARACHUTE - a canopy with the payoff under it.',
    'itemHealthSeek': 'HEALTH & SEEK - a lens over a cross. Go and find it.',
    'itemSecondSkin': 'SECOND SKIN - a body inside a second outline of itself.',
    'itemPhlebotomy': 'PHLEBOTOMY - a tube tipped out, three ways at once.',
    'crowbar': 'CROWBAR - a pry bar, and the rounds a swing pays out.',
    'harmWands': 'HARM WANDS - a magazine whose bottom half is moving.',
    'tightrope': 'TIGHTROPE - a figure on a wire, with air under it.',
    'runningOnFumes': 'RUNNING ON FUMES - the last segment of the bar, alight.',
    'ironLiturgy': 'IRON LITURGY - the crit ring, with a chapel cross in it.',
    'pityParty': 'PITY PARTY - four tally marks and the fifth struck through.',
    'redHarvest': 'RED HARVEST - the crit ring, and a drop falling out of it.',
    'feverDream': 'FEVER DREAM - a skull with the fever coming off it.',
    'longHaul': 'LONG HAUL - an hourglass, most of it run.',
    'secondaryInfection': 'SECONDARY INFECTION - three drops, each bigger.',
    'underfed': 'UNDERFED - a ribcage with nothing on it.',
    'coldBlood': 'COLD BLOOD - a heart with a plate over its lower quarter.',
    'freshBandages': 'FRESH BANDAGES - a roll of dressing, unwinding.',
    'curtainCall': 'CURTAIN CALL - a drawn curtain with a cross on the stage.',
    'slowRelease': 'SLOW RELEASE - a drip bag, and one drop under it.',
    'strayMercy': 'STRAY MERCY - a round coming in, and the cross it becomes.',
    'gristle': 'GRISTLE - a bone with a point growing off it.',
    'highInterest': 'HIGH INTEREST - a stack of coins and an arrow off the top.',
    'paperTrail': 'PAPER TRAIL - a receipt, torn at the foot.',
    'moneyBelt': 'MONEY BELT - a belt whose buckle is a coin.',
    'fireSale': 'FIRE SALE - a price tag on fire.',
    'movingDay': 'MOVING DAY - a crate: a coin in, a round out.',
    'raffleTicket': 'RAFFLE TICKET - a notched stub with a cell bolt on it.',
    'updraft': 'UPDRAFT - a figure held up by three chevrons.',
    'jackpot': 'JACKPOT - three reels, all sevens, and a full tray.',
    'scorchedEarth': 'SCORCHED EARTH - a skid across the floor, standing in fire.',
    'quorum': 'QUORUM - the sentry, and the ten marks that paid for it.',
    # ---- the fourth pool ---------------------------------------------------
    'syncopation': 'SYNCOPATION - four beats on a bar, and one off it, hitting.',
    'heartbeat': 'HEARTBEAT - a heart, and the pulse leaving it.',
    'oddCouple': 'ODD COUPLE - a pair in the magazine, and one over.',
    'evenBetter': 'EVEN BETTER - the same magazine, dividing cleanly.',
    'hotMag': 'HOT MAG - a full magazine, alight at the lips.',
    'pocketGrenade': 'POCKET GRENADE - an empty magazine and the last round going off.',
    'prodigalRounds': 'PRODIGAL ROUNDS - a round wide of the target, turning back.',
    'fullLoad': 'FULL LOAD - three rounds, racked, under the line they filled to.',
    'longArm': 'LONG ARM - a stock, and the distance it now covers.',
    'scythe': 'SCYTHE - the tool. The arc IS the pick.',
    'throatCut': 'THROAT CUT - a bar half gone, and the cut at the line.',
    'ballastTanks': 'BALLAST TANKS - two pressure tanks, and the level in them.',
    'plasmaBag': "PLASMA BAG - the shield's hexagon with the health cross in it.",
    'flowReload': 'FLOW RELOAD - a magazine going in, inside a ring.',
    'bellows': 'BELLOWS - the tool. Air, held, rather than air moving.',
    'sterileField': 'STERILE FIELD - a cross in a closed ring, and what it put out.',
    'crashCart': 'CRASH CART - a cross on wheels. The only wheels in the set.',
    'bedbugs': 'BEDBUGS - a bug, and the lesser one behind it.',
    'splashback': 'SPLASHBACK - a plate struck at an angle, and the spray back off it.',
    'sharedMag': 'SHARED MAG - the sentry, belt-fed from a magazine that is not its own.',
    'venomgrid': 'VENOMGRID - the same sentry, with a drop at the muzzle.',
    'hellspitter': 'HELLSPITTER - the same sentry again, with a flame at it.',
    'vintageOrbs': 'VINTAGE ORBS - a coin that is also a clock.',
    'firstFruits': 'FIRST FRUITS - three of them, on the stem. The count is the pick.',
    'coldFoot': 'COLD FOOT - a boot leaving, and ice standing where it went.',
    'jumperCables': 'JUMPER CABLES - two clamps and the jump between them.',
    'dimeNovel': 'DIME NOVEL - a paperback with a bullseye on the cover.',
}


def draw(name):
    c = Canvas()
    A.ICONS[name](c)
    if name not in A.RAW:
        A.finish(c)
    return c.rows()


def build():
    out = []
    for name in A.ICONS:
        rows = draw(name)
        note = NOTE.get(name)
        if note:
            out.append('  // ' + note)
        out.append('  %s: [' % name)
        out.extend("    '%s'," % r for r in rows)
        out.append('  ],')
    return '\n'.join(out)


if __name__ == '__main__':
    src = open(TARGET).read()
    head = 'const PIXEL_ICONS = {\n'
    a = src.index(head) + len(head)
    b = src.index('\n};', a)
    # Built in full BEFORE the file is opened for writing: `open(w)` truncates,
    # and a draw() that raises after that point leaves nothing behind.
    out = src[:a] + build() + src[b:]
    open(TARGET, 'w').write(out)
    print('%d icons written' % len(A.ICONS))
